# Site settings
title: Adam At Last
email: AdamAtLastMusic@gmail.com
url: https://www.AdamAtLast.com
description: "After all these years, it's Adam At Last."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: AdamAtLast.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/
  - title: facebook
    url: https://facebook.com/
  - title: youtube
    url: https://youtube.com/
# Build settings
markdown: kramdown
permalink: pretty
