# Site settings
title: Adam At Last
email: AdamAtLastMusic@gmail.com
url: https://www.AdamAtLast.com
description: ""

baseurl: /

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: AdamAtLast.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: soundcloud
    url: https://soundcloud.com/adam-at-last/
  - title: facebook
    url: https://www.facebook.com/AdamAtLastMusic/
  - title: youtube
    url: https://www.youtube.com/channel/UCrROyP3Xv7URZukyQBZTlvw
# Build settings
markdown: kramdown
permalink: pretty
